export const Images = {
    cut1: require('./Pics/cut1.PNG'),
    cut2: require('./Pics/cut2.PNG'),
    cut3: require('./Pics/cut3.PNG'),
    cut4: require('./Pics/cut4.PNG'),
    cut5: require('./Pics/cut5.PNG'),
    cut6: require('./Pics/cut6.PNG'),
    cut7: require('./Pics/cut7.PNG'),
    cut8: require('./Pics/cut8.PNG'),
    cut9: require('./Pics/cut9.PNG'),
    cut10: require('./Pics/cut10.PNG'),
    cut11: require('./Pics/cut11.PNG'),
    cut12: require('./Pics/cut12.PNG'),
    cut13: require('./Pics/cut13.PNG'),
    cut14: require('./Pics/cut14.PNG'),
    cut15: require('./Pics/cut15.PNG'),
    cut16: require('./Pics/cut16.PNG'),
    cut17: require('./Pics/cut17.PNG'),
    cut18: require('./Pics/cut18.PNG'),
    cut19: require('./Pics/cut19.PNG'),
    cut20: require('./Pics/cut20.PNG'),
    cut21: require('./Pics/cut21.PNG'),
    cut22: require('./Pics/cut22.PNG'),
    cut23: require('./Pics/cut23.PNG'),
    cut24: require('./Pics/cut24.PNG'),
    cut25: require('./Pics/cut25.PNG'),
    cut26: require('./Pics/cut26.PNG'),
    cut27: require('./Pics/cut27.PNG')
  
}